### ISSUE TITLE
FtlCwikiTemplateRenderer.groovy out-of-date

### ISSUE THREAD

**Issue by igorgallingani** [moqui/moqui-wikitext#1]
In file moqui-wikitext/src/main/groovy/org/moqui/wikitext/FtlCwikiTemplateRenderer.groovy

the code is out-of-date
ResourceReference rr = ecfi.getResourceFacade().getLocationReference(location);

Replace with
ResourceReference rr = ecfi.getResource().getLocationReference(location);

**Comment by jonesde** [comment]
Thank you, this is resolved in commit #5526ec7.
